import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { SignInButton, UserButton, useUser, SignIn,SignOut} from "@clerk/nextjs";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const  user = useUser()

  return (
          <>
          <Head>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#020617] to-[#0f172a]">
          <div>

          {!user.isSignedIn && <SignIn/>}
          {!!user.isSignedIn && <SignOut/>}
          </div>
          </main>
          </>
         );
};

export default Home;
